# Generated by Django 2.0.3 on 2020-04-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='toppings',
        ),
        migrations.AddField(
            model_name='topping',
            name='orders',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.OrderItem'),
        ),
    ]
