# Generated by Django 2.0.3 on 2020-04-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200416_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='orders',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='orders', to='orders.Topping'),
        ),
    ]
