# Generated by Django 2.0.3 on 2020-04-16 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.Price'),
        ),
    ]
