# Generated by Django 2.0.3 on 2020-04-20 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200417_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_pay',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
